from __future__ import annotations

from stats.pretty import PrettyLayoutSpec, PrettyLineSpec, field, list_item

BASIC_INNER_LAYOUT = PrettyLayoutSpec(
    fields={
        "state_apparatus_size": field("state_apparatus_size", "Размер аппарата", decimals=0, suffix="%", aliases=("Размер",)),
        "state_apparatus_efficiency": field("state_apparatus_efficiency", "Эфф. аппарата", decimals=0, suffix="%", aliases=("Эффективность",)),
        "knowledge_level": field("knowledge_level", "Уровень образования", decimals=0, aliases=("Уровень образованности",)),
        "success_chance": field("success_chance", "Шанс на успех", decimals=1, suffix="%", read_only=True, default=0.0),
        "many_children_propoganda": field("many_children_propoganda", "Пропаганда многодетности", decimals=0),
        "integrity_of_faith": field("integrity_of_faith", "Целостность веры", decimals=0),
        "corruption_level": field("corruption_level", "Коррупция", decimals=0),
        "salt_security": field("salt_security", "Солевой достаток", decimals=0, suffix="%"),
        "poor_level": field("poor_level", "Процент бедности", decimals=1),
        "jobless_level": field("jobless_level", "Процент безработицы", decimals=1),
        "income_from_scientific": field("income_from_scientific", "Доход науки", decimals=1, suffix=" ед.вал", aliases=("Доход от научных предприятий",)),
        "small_enterprise_percent": field("small_enterprise_percent", "Предприниматели", decimals=1, aliases=("Процент предпринимателей",)),
        "large_enterprise_count": field("large_enterprise_count", "Крупные предприниматели", decimals=0, aliases=("Количество крупных предпринимателей",)),
        "provinces_count": field("provinces_count", "Провинции", decimals=0, aliases=("Число провинций",)),
        "provinces_waste": field("provinces_waste", "Траты на провинцию", decimals=1, suffix=" ед.вал", aliases=("Траты на одну",)),
        "military_equipment": field("military_equipment", "ЗВО", decimals=1),
        "control0": list_item("control", "Правящая сила", 0, decimals=1, suffix="%"),
        "control1": list_item("control", "Представительство", 1, decimals=1, suffix="%"),
        "control2": list_item("control", "Имеющие силу", 2, decimals=1, suffix="%"),
        "control3": list_item("control", "Автономии", 3, decimals=1, suffix="%"),
        "contentment": field("contentment", "Довольство населения", decimals=0),
        "government_trust": field("government_trust", "Доверие властям", decimals=1),
        "many_children_traditions": field("many_children_traditions", "Традиции многодетности", decimals=0),
        "sexual_asceticism": field("sexual_asceticism", "Сексуальный аскетизм", decimals=1),
        "egocentrism_development": field("egocentrism_development", "Эгоцентризм развития", decimals=1),
        "education_level": field("education_level", "Образованность", decimals=1),
        "erudition_will": field("erudition_will", "Стремление к эрудиции", decimals=0),
        "cultural_level": field("cultural_level", "Уровень культуры", decimals=0),
        "violence_tendency": field("violence_tendency", "Склонность к насилию", decimals=1),
        "panic_level": field("panic_level", "Паника", decimals=1, suffix="%"),
        "society_decline": field("society_decline", "Упадок общества", decimals=1, suffix="%", read_only=True, default=0.0),
        "unemployment_rate": field("unemployment_rate", "Процент тунеядства", decimals=1),
        "grace_of_the_highest": field("grace_of_the_highest", "Милость Высших", decimals=0),
        "commitment_to_cause": field("commitment_to_cause", "Убеждённость Делу", decimals=0, aliases=("Собственная Убеждённость Делу",)),
        "departure_from_truths": field("departure_from_truths", "Отхождение от истин", decimals=0),
    },
    lines=(
        PrettyLineSpec(title="ГОСУДАРСТВО"),
        PrettyLineSpec(fields=("state_apparatus_size", "state_apparatus_efficiency", "knowledge_level")),
        PrettyLineSpec(fields=("success_chance", "many_children_propoganda", "integrity_of_faith")),
        PrettyLineSpec(fields=("corruption_level", "salt_security", "poor_level")),
        PrettyLineSpec(fields=("jobless_level", "income_from_scientific", "small_enterprise_percent")),
        PrettyLineSpec(fields=("large_enterprise_count", "provinces_count", "provinces_waste")),
        PrettyLineSpec(fields=("military_equipment", "control0", "control1")),
        PrettyLineSpec(fields=("control2", "control3", "contentment")),
        PrettyLineSpec(title="НАРОД"),
        PrettyLineSpec(fields=("government_trust", "many_children_traditions", "sexual_asceticism")),
        PrettyLineSpec(fields=("egocentrism_development", "education_level", "erudition_will")),
        PrettyLineSpec(fields=("cultural_level", "violence_tendency", "panic_level")),
        PrettyLineSpec(fields=("society_decline", "unemployment_rate")),
        PrettyLineSpec(fields=("grace_of_the_highest", "commitment_to_cause", "departure_from_truths")),
    ),
)

ATTERIUM_INNER_LAYOUT = PrettyLayoutSpec(
    fields={
        **{k: v for k, v in BASIC_INNER_LAYOUT.fields.items() if k not in {"income_from_scientific", "small_enterprise_percent", "large_enterprise_count", "egocentrism_development", "grace_of_the_highest"}},
        "state_apparatus_functionality": field("state_apparatus_functionality", "Связь Федерации", decimals=1, suffix="%", aliases=("Cвязь Федерации с Республиками",)),
        "small_enterprise_percent": field("small_enterprise_percent", "Малый бизнес", decimals=1),
        "large_enterprise_count": field("large_enterprise_count", "Клюпр Цесаркии", decimals=0),
        "egocentrism_development": field("egocentrism_development", "БТЗГ", decimals=1),
        "capitalistic_decay": field("capitalistic_decay", "Кап. разложение", decimals=1, aliases=("Капиталистическое разложение",)),
        "equality": field("equality", "Равенство", decimals=1, suffix="%"),
        "grace_of_the_highest": field("grace_of_the_highest", "Милость Высших", decimals=0),
    },
    lines=(
        PrettyLineSpec(title="ГОСУДАРСТВО"),
        PrettyLineSpec(fields=("state_apparatus_functionality", "state_apparatus_size", "state_apparatus_efficiency")),
        PrettyLineSpec(fields=("knowledge_level", "success_chance", "many_children_propoganda")),
        PrettyLineSpec(fields=("integrity_of_faith", "corruption_level", "salt_security")),
        PrettyLineSpec(fields=("poor_level", "jobless_level", "small_enterprise_percent")),
        PrettyLineSpec(fields=("large_enterprise_count", "provinces_count", "provinces_waste")),
        PrettyLineSpec(fields=("military_equipment", "control0", "control1")),
        PrettyLineSpec(fields=("control2", "control3", "contentment")),
        PrettyLineSpec(title="НАРОД"),
        PrettyLineSpec(fields=("government_trust", "many_children_traditions", "sexual_asceticism")),
        PrettyLineSpec(fields=("egocentrism_development", "capitalistic_decay", "education_level")),
        PrettyLineSpec(fields=("erudition_will", "cultural_level", "violence_tendency")),
        PrettyLineSpec(fields=("panic_level", "society_decline", "unemployment_rate")),
        PrettyLineSpec(fields=("equality", "grace_of_the_highest")),
        PrettyLineSpec(fields=("commitment_to_cause", "departure_from_truths")),
    ),
)

ISF_INNER_LAYOUT = PrettyLayoutSpec(
    fields={
        **{k: v for k, v in BASIC_INNER_LAYOUT.fields.items() if k not in {"income_from_scientific", "small_enterprise_percent", "large_enterprise_count", "control0", "control2", "grace_of_the_highest"}},
        "small_enterprise_percent": field("small_enterprise_percent", "Малый бизнес", decimals=1),
        "large_enterprise_count": field("large_enterprise_count", "Аристокр. дома", decimals=0, aliases=("Аристократические и коммерческие дома",)),
        "allegory_influence": field("allegory_influence", "Влияние Аллегории", decimals=1, suffix="%"),
        "control0": list_item("control", "Императорский двор", 0, decimals=1, suffix="%"),
        "control2": list_item("control", "Аристократия", 2, decimals=1, suffix="%"),
        "imperial_court_power": field("imperial_court_power", "Сила Имперского Двора", decimals=1, suffix="%"),
        "grace_of_the_silver": field("grace_of_the_silver", "Милость Серебрянной", decimals=0),
        "separatism_of_the_highest": field("separatism_of_the_highest", "Сепаратизм Высших", decimals=0),
    },
    lines=(
        PrettyLineSpec(title="ГОСУДАРСТВО"),
        PrettyLineSpec(fields=("state_apparatus_size", "state_apparatus_efficiency", "knowledge_level")),
        PrettyLineSpec(fields=("success_chance", "many_children_propoganda", "integrity_of_faith")),
        PrettyLineSpec(fields=("corruption_level", "salt_security", "poor_level")),
        PrettyLineSpec(fields=("jobless_level", "small_enterprise_percent", "large_enterprise_count")),
        PrettyLineSpec(fields=("provinces_count", "provinces_waste", "military_equipment")),
        PrettyLineSpec(fields=("allegory_influence", "control0", "control1")),
        PrettyLineSpec(fields=("control2", "control3", "contentment")),
        PrettyLineSpec(title="НАРОД"),
        PrettyLineSpec(fields=("government_trust", "many_children_traditions", "sexual_asceticism")),
        PrettyLineSpec(fields=("egocentrism_development", "education_level", "erudition_will")),
        PrettyLineSpec(fields=("cultural_level", "violence_tendency", "panic_level")),
        PrettyLineSpec(fields=("society_decline", "unemployment_rate", "imperial_court_power")),
        PrettyLineSpec(fields=("grace_of_the_silver", "commitment_to_cause")),
        PrettyLineSpec(fields=("departure_from_truths", "separatism_of_the_highest")),
    ),
)
